#!/bin/bash

echo "Render PostgreSQL Database Setup"
echo "================================="
echo ""
echo "This script will help you set up a Render PostgreSQL database"
echo ""

cd /home/caiweihao/booleangame/my-app

echo "Step 1: Open Render Dashboard"
echo "------------------------------"
echo "Please open: https://dashboard.render.com"
echo "Login with your GitHub account"
echo ""

echo "Step 2: Create PostgreSQL Database"
echo "-----------------------------------"
echo "1. Click 'New' → 'PostgreSQL'"
echo "2. Enter the following:"
echo "   Name: blog-news-db"
echo "   Database: blognews"
echo "   User: bloguser"
echo "3. Click 'Create Database'"
echo ""

echo "Step 3: Wait for database to be ready"
echo "--------------------------------------"
echo "Wait 1-2 minutes for the database to be created"
echo ""

echo "Step 4: Get Connection String"
echo "------------------------------"
echo "1. Click on your database 'blog-news-db'"
echo "2. Find 'Connections' section"
echo "3. Copy 'External Database URL'"
echo "   It looks like: postgres://bloguser:password@host:5432/blognews"
echo ""

echo "Step 5: Configure Vercel"
echo "------------------------"
echo "Visit: https://vercel.com/caiweihao-s-projects/my-app/settings/environment-variables"
echo ""
echo "Add these environment variables:"
echo ""
echo "Name: DATABASE_URL"
echo "Value: [paste the connection string from step 4]"
echo ""
echo "Name: NEXTAUTH_SECRET"
echo "Value: $(openssl rand -base64 32 2>/dev/null || head -c 64 /dev/urandom | base64 | head -c 32)"
echo ""
echo "Click 'Save'"
echo ""

echo "Step 6: Run Database Migration"
echo "-------------------------------"
echo "After setting environment variables, run:"
echo ""
echo "  cd /home/caiweihao/booleangame/my-app"
echo "  npx prisma migrate deploy"
echo "  npm run db:seed"
echo ""

echo "Step 7: Redeploy"
echo "---------------"
echo "  vercel --prod"
echo ""

echo "Done! Your website should be working now."
echo ""
